# Numpy

Numerical Python is a Python Library written in C that allows for very fast computations. At its core is the ndarray (n-dimensional). An ndarray is a multidimensional array of elements all of the same type. An ndarray is a grid that can take on many shapes and can hold either numbers or strings.

In [2]:
import numpy as np

# create a 1D ndarray that contains only integers
x = np.array([1,2,3,4,5])

print('x = ', x)

x =  [1 2 3 4 5]


### ndarrays attributes

We refer to 1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. Therefore, we refer to a 2D array as a rank 2 array.

Another important property of arrays is their shape. The shape of an array is the size along each of its dimensions. For example, the shape of a rank 2 array will correspond to the number of rows and columns of the array. The shape of an ndarray can be obtained using the .shape attribute. The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. In the example below we will create a rank 1 array and learn how to obtain its shape, its type, and the data-type (dtype) of its elements.

In [4]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [11]:
Y = np.array([[1,2,3,4,5],[5,6,7,8,9]])
Z = np.array([[11,12,13], [34,45,65],[99,87,76], [77,54,33]])
print(Y,Z)

[[1 2 3 4 5]
 [5 6 7 8 9]] [[11 12 13]
 [34 45 65]
 [99 87 76]
 [77 54 33]]


Once you create an ndarray, you may want to save it to a file to be read later or to be used by another program. NumPy provides a way to save the arrays into files for later use

In [12]:
x = np.array([1,2,3,4,5])

np.save('my_array', x)

In [16]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


# Using Built-in Functions to Create ndarrays

Numpy offers the ability to create ndarrays using built-in functions. These functions allow us to create certain kinds of ndarrays with just one line of code.

In [26]:
# Create a 3x4 ndarray full of zeros
X = np.zeros((3,4))

print(X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

# We create a 3 x 2 ndarray full of ones. 
ones = np.ones((3,2))
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
# To create an ndarray full of any other values we use full()
z = np.full((4,4), 5)

print(z)
print()

print(z.shape)
print(type(z))
print(z.dtype)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

(4, 4)
<class 'numpy.ndarray'>
int64


A fundamental array in Linear Algebra is the Identity Matrix. An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 

In [31]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
# np.diag() allows to create a matrix with specific values on its main diagonal
new = np.diag([7,20,30,40])
print(new)
print()

print(new.shape)
print(type(new))
print(new.dtype)

[[ 7  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

(4, 4)
<class 'numpy.ndarray'>
int64


### np.arange()

The function np.arange(4,10) generates a sequence of integers with 4 inclusive and 10 exclusive.

When used with three arguments, np.arange(start,stop,step) will create a rank 1 ndarray with evenly spaced values 

within the half-open interval [start, stop) with step being the distance between two adjacent values. NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments. Below we will see examples of each case and how they are used to create different kinds of ndarrays.

In [42]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


### np.linspace()

Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace(). 

The *np.linspace(start, stop, N)* function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values.

In [41]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


#### Creating n-darrays using np.arrange() or linspace() with reshape()

We can use np.arange() and np.linspace() functions to create rank 2 ndarrays of any shape by combining them with the np.reshape() function. 

The np.reshape(ndarray, new_shape) function converts the given ndarray into the specified new_shape. It is important to note that the new_shape should be compatible with the number of elements in the given ndarray. For example, you can convert a rank 1 ndarray with 6 elements, into a 3 x 2 rank 2 ndarray, or a 2 x 3 rank 2 ndarray, since both of these rank 2 arrays will have a total of 6 elements. However, you can't reshape the rank 1 ndarray with 6 elements into a 3 x 3 rank 2 ndarray, since this rank 2 array will have 9 elements, which is greater than the number of elements in the original ndarray. Let's see some examples:

In [43]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [40]:
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,33, 2)
X = np.reshape(X, (4,4))
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


## Accessing, Deleting, and Inserting Elements Into ndarrays

NumPy ndarrays are mutable, meaning that the elements in ndarrays can be changed after the ndarray has been created. NumPy ndarrays can also be sliced, which means that ndarrays can be split in many different ways. This allows us, for example, to retrieve any subset of the ndarray that we want. 